name: "Textile Bucket - Deploy"
on:
  push:
    branches:
      - main
jobs:
  deploy: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: push # push to a known bucket
        id: bucket
        uses: "textileio/github-action-buckets@master"
        with:
          key: ${{ secrets.BUCKET_KEY }}
          secret: ${{ secrets.BUCKET_SECRET }}
          bucket: "bafzbeigunr7rw7weammzaqryofc3ya3raw7lilnvchg4vf6h5xgcjbwuhi"
          thread: "bafk4ruiez2yyfjxytdmavnwa2vd4pq75ac44baxcan4hwe24sqdiyqi"
          path: "./tableland-todo/dist"
      - run: echo "bucket - ${{ steps.bucket.outputs.key }}"
      - run: echo "ipfs - ${{ steps.bucket.outputs.ipfs }}"
      - run: echo "ipfs link - ${{ steps.bucket.outputs.ipfsUrl }}"
      - run: echo "ipns - ${{ steps.bucket.outputs.ipns }}"
      - run: echo "ipns link - ${{ steps.bucket.outputs.ipnsUrl }}"
      - run: echo "hub - ${{ steps.bucket.outputs.hub }}"
      - run: echo "www - ${{ steps.bucket.outputs.www }}"
